export const ADD_NOTE = "ADD_NOTE";
export const REMOVE_NOTE = "REMOVE_NOTE";

export const HEART_NOTE = "HEART_NOTE";
export const FAVORITE_NOTE = "FAVORITE_NOTE";
export const UPDATE_TITLE_AND_DESCRIPTION = "UPDATE_TITLE_AND_DESCRIPTION";

export const CHANGE_FILTERS = "CHANGE_FILTERS";
export const APPLY_FILTERS = "APPLY_FILTERS";

export const MENU_VISIBLE = "MENU_VISIBLE";
